"""followers

Revision ID: 586227683538
Revises: a0bfdb827949
Create Date: 2019-11-28 16:01:42.191615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586227683538'
down_revision = 'a0bfdb827949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
